version: '3.7'
services:
  mysql:
    image: ${MYSQL_IMAGE:-percona/percona-server}
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command:
      - --log-output=NONE
