required = [
  "github.com/golang/protobuf/protoc-gen-go",
  "golang.org/x/tools/cmd/goimports",
  "github.com/percona/mysqld_exporter",
]

[[override]]
  name = "github.com/percona/mysqld_exporter"
  branch = "master"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
